### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by LazyGuyWithRSI** [refracta/dcss-webtiles-server#104]
I would like to use your repo as a jumping off point for a North American server, however there is no license. I was hoping for clarification on if I could use your wonderful dockerized code (I gave myself a headache trying to dockerize dgl).

**Comment by refracta** [comment]
I have specified the repository's license as GPLv3. I am in the process of obtaining consent from the [Crawl Team](https://github.com/crawl) and [Sentei](https://github.com/Rytisgit), who created the original code base, and I believe it will be fine for you to use this repository's code under the GPLv3 license. 
*After discussing with the Crawl Team, it seems that the [dgamelaunch-config](https://github.com/crawl/dgamelaunch-config) repository will also have the GPLv3 license specified soon.

**Comment by refracta** [comment]
I have been given permission to use the license.
